openapi: 3.0.1
info:
  title: csvkit
  description: CSVKit to covert from and to CSV
  version: "1.0"
  x-direktiv-meta:
    container: gcr.io/direktiv/functions/csvkit
    maintainer: "[direktiv.io](https://www.direktiv.io) "
    issues: https://github.com/direktiv-apps/csvkit/issues
    url: https://github.com/direktiv-apps/csvkit
    categories:
    - misc
    - docs
    license: "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)"
    long-description: "CSVKit is a suite of utilities for converting to and working\
      \ with CSV. Version 1.0.7 is installed for this function. All available command\
      \ are installed and can be looked up [here](https://csvkit.readthedocs.io/en/latest/index.html).\
      \ \nThis function can run a list of commands but additionally accepts a `convert`\
      \ property which can point to a file.  This file will be converted to CSV and\
      \ stored in Direktiv's instance scope. This file can be accessed via `out/instance/out.csv`."
servers:
- url: /
paths:
  /:
    post:
      parameters:
      - name: Direktiv-ActionID
        in: header
        description: "direktiv action id is an UUID. \nFor development it can be set\
          \ to 'development'\n"
        schema:
          type: string
          default: development
      - name: Direktiv-TempDir
        in: header
        description: |
          direktiv temp dir is the working directory for that request
          For development it can be set to e.g. '/tmp'
        schema:
          type: string
          default: /tmp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: array
                  description: File to create before running commands.
                  items:
                    $ref: '#/components/schemas/direktivFile'
                convert:
                  type: string
                  description: converts incoming file and stores it under instance
                    context.
                commands:
                  type: array
                  description: Array of commands.
                  items:
                    type: object
                    properties:
                      command:
                        type: string
                        description: Command to run
                      silent:
                        type: boolean
                        description: If set to false the command will not print output
                          to logs.
                        default: false
                      print:
                        type: boolean
                        description: If set to false the command will not print the
                          full command with arguments to logs.
                        default: true
                      continue:
                        type: boolean
                        description: "Stops excecution if command fails, otherwise\
                          \ proceeds with next command"
        required: false
      responses:
        "200":
          description: List of executed commands.
          content:
            application/json:
              schema:
                type: object
                properties:
                  csvkit:
                    type: array
                    items:
                      required:
                      - result
                      - success
                      type: object
                      properties:
                        success:
                          type: boolean
                        result:
                          type: object
            csvkit:
              example:
              - result:
                - Header1: Value1
                  Header2: Value2
                success: true
        default:
          description: generic error response
          headers:
            Direktiv-ErrorMessage:
              schema:
                type: string
            Direktiv-ErrorCode:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-direktiv-function: |-
        functions:
        - id: csvkit
          image: gcr.io/direktiv/functions/csvkit:1.0
          type: knative-workflow
      x-direktiv-examples:
      - title: Basic
        content: "- id: csvkit\n  type: action\n  action:\n    function: csvkit\n\
          \    files: \n    - key: data.xlsx\n      scope: workflow\n    input: \n\
          \      convert: data.xlsx\n      commands:\n      - command: csvjson out/instance/out.csv"
      - title: Advanced
        content: "- id: csvkit\n  type: action\n  action:\n    function: csvkit\n\
          \    files: \n    - key: data.xlsx\n      scope: workflow\n    input: \n\
          \      convert: data.xlsx\n      commands:\n      - command: csvcut -c 1\
          \ out/instance/out.csv"
      x-direktiv:
        cmds:
        - action: exec
          exec: "{{- if .Convert }}\nbash -c 'in2csv {{ .Convert }} > out/instance/out.csv'\n\
            {{- else }}\necho \"\"\n{{- end }}  "
        - action: foreach
          loop: .Commands
          exec: "{{ .Item.Command }}"
          silent: "{{ .Item.Silent }}"
          print: "{{ .Item.Print }}"
          continue: "{{ .Item.Continue }}"
        output: |
          {
            "csvkit": {{ index . 1 | toJson }}
          }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      x-codegen-request-body-name: body
components:
  schemas:
    direktivFile:
      type: object
      x-go-type:
        type: DirektivFile
        import:
          package: github.com/direktiv/apps/go/pkg/apps
    error:
      required:
      - errorCode
      - errorMessage
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string

